import _ from 'lodash';

const characters = [
  ['你', 'nǐ', 'you'],
  ['好', 'hǎo', 'good'],
  ['再', 'zài', 'again'],
  ['见', 'jiàn', 'see'],
  ['零', 'líng', 'zero'],
  ['一', 'yī', 'one'],
  ['二', 'èr', 'two'],
  ['三', 'sān', 'three'],
  ['四', 'sì', 'four'],
  ['五', 'wǔ', 'five'],
  ['六', 'liù', 'six'],
  ['七', 'qī', 'seven'],
  ['八', 'bā', 'eight'],
  ['九', 'jiǔ', 'nine'],
  ['十', 'shí', 'ten'],
  ['百', 'bǎi', 'hundred'],
  ['我', 'wǒ', 'me'],
  ['叫', 'jiào', 'called'],
  ['吗', 'ma', 'question marker'],
  ['人', 'rén', 'person'],
  ['女', 'nǚ', 'female'],
  ['男', 'nán', 'male'],
  ['孩', 'hái', 'child'],
  ['高兴', 'gāoxìng', 'happy (high happy)'],
  ['也', 'yĕ', 'also'],
  ['认识', 'rènshí', 'to know (both characters seem to also mean this individually?)'],
  ['王', 'wáng', 'king/a common surname'],
  ['李', 'lǐ', 'a common surname'],
  ['很', 'hĕn', 'very'],
  ['名字', 'míngzi', 'name character'],
  ['姓', 'xìng', 'surname'],
  ['什么', 'shénme', 'what / interrogative'],
  ['是', 'shì', 'to be'],
  ['元', 'yuán', 'Chinese currency (RMB)'],
  ['的', 'de', 'makes personal pronouns possessive'],
  ['果', 'guŏ', 'fruit'],
  ['水', 'shuĭ', 'water'],

  ['鱼', 'yú', 'fish'],
  ['面', 'miàn', 'noodles'],
  ['吃', 'chī', '	eat'],
  ['饭', 'fàn', 'rice / meal'],
  ['喝', 'hē', '	to drink'],
  ['茶', 'chá', 'tea'],
  ['不', 'bù', 'not'],
  ['呢', 'ne', 'and'],

  ['学', 'xué', 'to study'],
  ['他', 'tā', 'he'],
  ['她', 'tā', 'she'],
  ['生', 'shēng', 'livelihood'],
  ['学生', 'xuéshēng', 'student'],
  ['们', 'men', 'plural suffix'],
  ['老', 'lăo', 'old/wise'],
  ['医', 'yī', 'doctor'],
  ['师', 'shī', 'master/teacher'],
  ['张', 'zhang', 'a common surname']
];

export function getShuffledCharacters() {
  return _.shuffle(characters).map(c => ({
    chinese: c[0],
    pinyin: c[1],
    english: c[2],
  }));
}
